#!/bin/bash

# ======================================
# ANSI
# ======================================
ansi_reset='\e[0m'

blue='\e[34m'

yellow_b='\e[1;33m'

red_b='\e[1;31m'


# ======================================
# Constants
# ======================================
svg_source="icons.svg"

svg_src_tmp="/tmp/icons.svg"

default_color="#4078c0"

default_size=32

icon_index="index.txt"


# ======================================
# User Input
# ======================================
echo "Enter icon size (skip for default icon dimensions): "
read -r icon_size

echo "Enter 1 or more colors (space or tab separated): "
read -r -a icon_color


# ======================================
# Checks
# ======================================
# If no colors given, add default color to array
[ ${#icon_color[*]} -eq 0 ] && icon_color[0]=$default_color

icon_size=${icon_size:-"$default_size"}


# ======================================
# RENDER
# ======================================
for color in ${icon_color[*]}; do

    mkdir -p "${color}__$icon_size"


    trap 'rm $svg_src_tmp; exit' INT TERM


    cp "$svg_source" "$svg_src_tmp"


    # Change color of temp copy
    [ ! "$color" = "$default_color" ] &&
    sed -i "s/$default_color/$color/" "$svg_src_tmp"


    # Loop through index.txt & render png's
    while read -r i; do

        if [ -f "${color}__$icon_size/$i.png" ]; then
            echo -e "${red_b}${color}__$icon_size/$i.png exists.${ansi_reset}"

        else
            echo
            echo -e "${blue}Rendering ${yellow_b}${color}__$icon_size/$i.png${ansi_reset}"
            inkscape --export-id="${i}" \
                     --export-id-only \
                     --export-width="$icon_size" --export-height="$icon_size" \
                     --export-png="${color}__$icon_size/$i.png" "$svg_src_tmp" >/dev/null
        fi
    done < "$icon_index"


    # Remove copy before next iteration or EXIT
    rm "$svg_src_tmp"

done


# If notify-send installed, send notif
hash notify-send 2>/dev/null &&
notify-send -i 'terminal' \
            -a 'Terminal' \
            'Terminal'    \
            'Finished rendering icons!'
